import 'package:flutter/material.dart';

class Terms extends StatelessWidget {
  const Terms({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("About Us")),
      body: Container(
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage(
              "assets/images/background.png",
            ),
            fit: BoxFit.cover,
          ),
        ),
        child: Center(
          child: Column(
            children: [
              SizedBox(height: 25),
              Text(
                "Terms of Service",
                style: TextStyle(
                  fontSize: 25,
                  color: Colors.white,
                ),
              ),
              SizedBox(height: 15),
              Container(
                width: 365,
                padding: EdgeInsets.only(
                  left: 35,
                  right: 35,
                  top: 35,
                  bottom: 50,
                ),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(10),
                  border: Border.all(
                    color: Colors.black,
                    width: 2,
                  ),
                ),
                child: Text(
                  "By accessing or using Warmly, you agree to use the platform in a lawful, respectful, and responsible manner, and to ensure that all information you provide such as contacts, introductions, and notes is accurate and obtained with proper consent. You are fully responsible for maintaining the security of your account and any actions taken under it. Warmly provides tools to help streamline introductions, follow-ups, and investor management, but we do not guarantee communication outcomes, delivery of reminders, or the accuracy of insights generated by the system. We may update, modify, or discontinue features at any time as we improve the service. Warmly is not liable for data loss, missed opportunities, or damages resulting from how the platform is used. Continued use of the service indicates your acceptance of any updates to these terms, and if you do not agree, you should stop using Warmly immediately.",
                  style: TextStyle(fontSize: 15),
                  textAlign: TextAlign.justify,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
